# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gyroX', models.CharField(max_length=10)),
                ('gyroY', models.CharField(max_length=10)),
                ('gyroZ', models.CharField(max_length=10)),
                ('gpsLat', models.CharField(max_length=10)),
                ('gpsLon', models.CharField(max_length=10)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
