# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uimodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellite',
            old_name='name',
            new_name='title',
        ),
    ]
